const users =
[
   {
      "id":1,
      "name":"Mohammad",
      "email":"mohammad@gmail.com",
      "gender":"male",
      "mobile":"734-324-1043",
      "cumulativeGPA":92.1,
      "isGraduated":true,
      "friends":[
         {
            "name":"Magdalena",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":28,
      "image" : {"name":"ghklk.png", "height": 50 , "width":30},
   },
   {
      "id":2,
      "name":"Rami",
      "email":"lgilbee1@google.com.br",
      "gender":"male",
      "mobile":"165-705-3521",
      "cumulativeGPA":90.6,
      "isGraduated":true,
      "friends":[
         {
            "name":"Magdalena",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":23,
      "image" : {"name":"ghklk.png", "height": 50, "width":30},
   },
   {
      "id":3,
      "name":"Mohammad",
      "email":"hgaspero2@1688.com",
      "gender":"male",
      "mobile":"158-265-8979",
      "cumulativeGPA":87.9,
      "isGraduated":false,
      "friends":[
         {
            "name":"Magdalena",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":26,
      "image" : {"name":"ghrtlk.png", "height": 51, "width":31},
   },
   {
     "id":4,
     "name":"Ahmad",
     "email":"igummie3@blinklist.com",
     "gender":"male",
     "mobile":"832-900-3701",
     "cumulativeGPA":86.8,
     "isGraduated":true,
     "friends":[
        {
           "name":"Magdalena",
           "email":"mgrewes0@chronoengine.com",
           "gender":"male",
           "mobile":"734-324-1043",
           "cumulativeGPA":92.1
        },
        {
           "name":"Harman",
           "email":"hgaspero2@1688.com",
           "gender":"male",
           "mobile":"158-265-8979",
           "cumulativeGPA":87.9
        },
        {
           "name":"Oliver",
           "email":"ocourtliff4@spotify.com",
           "gender":"female",
           "mobile":"500-958-5193",
           "cumulativeGPA":67.9
        }
     ],
     "age":22,
     "image" : {"name":"ghklk.png", "height": 52, "width":32},
   },
   {
      "id":5,
      "name":"Oliver",
      "email":"ocourtliff4@spotify.com",
      "gender":"female",
      "mobile":"500-958-5193",
      "cumulativeGPA":67.9,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":21,
      "image" : {"name":"ghklk.png", "height": 53, "width":33}
   },
   {
      "id":6,
      "name":"Melodie",
      "email":"mspadoni5@usda.gov",
      "gender":"female",
      "mobile":"291-520-2857",
      "cumulativeGPA":87.5,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":20,
      "image" : {"name":"ghklk.png", "height": 54, "width":34}
   },
   {
      "id":7,
      "name":"Padraig",
      "email":"pstephens6@oaic.gov.au",
      "gender":"male",
      "mobile":"103-300-2320",
      "cumulativeGPA":81.6,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":24,
      "image" : {"name":"ghklk.png", "height": 35, "width":55}
   },
   {
      "id":8,
      "name":"Ahmad",
      "email":"fperford7@addthis.com",
      "gender":"male",
      "mobile":"659-325-0974",
      "cumulativeGPA":68.5,
      "isGraduated":true,
      "friends":[
         {
            "name":"Sndos",
            "email":"mgrewes0@chronoengine.com",
            "gender":"female",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"female",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":18,
      "image" : {"name":"ghkluk.png", "height": 30, "width":50}
   },
   {
      "id":9,
      "name":"Carlye",
      "email":"cjurisch8@google.de",
      "gender":"female",
      "mobile":"778-865-5596",
      "cumulativeGPA":63.1,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":27,
      "image" : {"name":"g8klk.png", "height": 51, "width":31}
   },
   {
      "id":10,
      "name":"Mohammad",
      "email":"bkatzmann9@earthlink.net",
      "gender":"male",
      "mobile":"652-615-7821",
      "cumulativeGPA":91.2,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":70.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":80.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":19,
      "image" : {"name":"ghkly.png", "height": 52, "width":32}
   },
   {
      "id":11,
      "name":"Devan",
      "email":"dwinwarda@is.gd",
      "gender":"female",
      "mobile":"532-766-1803",
      "cumulativeGPA":64.1,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":19,
      "image" : {"name":"ghklb.png", "height": 53, "width":33}
   },
   {
      "id":12,
      "name":"Nalani",
      "email":"nagerskowb@wikimedia.org",
      "gender":"female",
      "mobile":"822-614-5382",
      "cumulativeGPA":85.3,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":20,
      "image" : {"name":"grklk.png", "height": 54, "width":34}
   },
   {
      "id":13,
      "name":"Mohammad",
      "email":"achapellowc@deviantart.com",
      "gender":"male",
      "mobile":"887-813-5326",
      "cumulativeGPA":82.4,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":28,
      "image" : {"name":"giklk.png", "height": 54, "width":34}
   },
   {
      "id":14,
      "name":"Mohammad",
      "email":"rrederd@photobucket.com",
      "gender":"male",
      "mobile":"193-339-5604",
      "cumulativeGPA":88.8,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":80.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":82.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":19,
      "image" : {"name":"ghk8k.png", "height": 55, "width":35}
   },
   {
      "id":15,
      "name":"Jonell",
      "email":"jrustmane@nifty.com",
      "gender":"female",
      "mobile":"827-540-7207",
      "cumulativeGPA":94.1,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":21,
      "image" : {"name":"g9klk.png", "height": 50, "width":30}
   },
   {
      "id":16,
      "name":"Ahmad",
      "email":"bburkmanf@samsung.com",
      "gender":"male",
      "mobile":"478-875-2616",
      "cumulativeGPA":95.7,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":18,
      "image" : {"name":"ghklo.png", "height": 51, "width":31}
   },
   {
      "id":17,
      "name":"Holden",
      "email":"hcolquhoung@hugedomains.com",
      "gender":"male",
      "mobile":"508-850-8559",
      "cumulativeGPA":72.9,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":24,
      "image" : {"name":"ghkl7.png", "height": 52, "width":32}
   },
   {
      "id":18,
      "name":"Melonie",
      "email":"mjentleh@rakuten.co.jp",
      "gender":"male",
      "mobile":"812-415-1582",
      "cumulativeGPA":84.4,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":26,
      "image" : {"name":"gh8lk.png", "height": 53, "width":33}
   },
   {
      "id":19,
      "name":"Madison",
      "email":"msmealli@people.com.cn",
      "gender":"female",
      "mobile":"579-577-4131",
      "cumulativeGPA":65.0,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":19,
      "image" : {"name":"ghkl0.png", "height": 54, "width":34}
   },
   {
      "id":20,
      "name":"Dorine",
      "email":"dlivezeyj@ifeng.com",
      "gender":"male",
      "mobile":"975-499-4901",
      "cumulativeGPA":65.8,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":20,
      "image" : {"name":"gh0lk.png", "height": 57, "width":37}
   },
   {
      "id":21,
      "name":"Rania",
      "email":"mramplingk@bloglovin.com",
      "gender":"female",
      "mobile":"175-170-8778",
      "cumulativeGPA":95.4,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":22,
      "image" : {"name":"ghklk.png", "height": 58, "width":38}
   },
   {
      "id":22,
      "name":"Marlena",
      "email":"mgraverl@wikipedia.org",
      "gender":"female",
      "mobile":"435-314-1262",
      "cumulativeGPA":96.9,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         }
      ],
      "age":28,
      "image" : {"name":"gh7lk.png", "height": 58, "width":38}
   },
   {
      "id":23,
      "name":"Mohammad",
      "email":"romoylanem@omniture.com",
      "gender":"male",
      "mobile":"487-863-3754",
      "cumulativeGPA":83.3,
      "isGraduated":true,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":27,
      "image" : {"name":"ghk8k.png", "height": 50, "width":30}
   },
   {
      "id":24,
      "name":"Concordia",
      "email":"ccarseyn@gizmodo.com",
      "gender":"female",
      "mobile":"108-330-3447",
      "cumulativeGPA":88.6,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"female",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":20,
      "image" : {"name":"g5klk.png", "height": 51, "width":31}
   },
   {
      "id":25,
      "name":"Angie",
      "email":"aplanteo@irs.gov",
      "gender":"male",
      "mobile":"467-337-4282",
      "cumulativeGPA":71.6,
      "isGraduated":false,
      "friends":[
         {
            "name":"Roba",
            "email":"mgrewes0@chronoengine.com",
            "gender":"female",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":19,
      "image" : {"name":"ghk9k.png", "height": 52, "width":32}
   },
   {
      "id":26,
      "name":"Marice",
      "email":"mhuginp@rediff.com",
      "gender":"female",
      "mobile":"398-495-7771",
      "cumulativeGPA":85.0,
      "isGraduated":false,
      "friends":[
         {
            "name":"Lama",
            "email":"mgrewes0@chronoengine.com",
            "gender":"female",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":19,
      "image" : {"name":"ghklk.png", "height": 53, "width":37}
   },
   {
      "id":27,
      "name":"Delaney",
      "email":"dendecottq@geocities.com",
      "gender":"male",
      "mobile":"278-730-9674",
      "cumulativeGPA":89.2,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"female",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":28,
      "image" : {"name":"ghklk.png", "height": 50, "width":30}
   },
   {
      "id":28,
      "name":"Rosemonde",
      "email":"rlawlyr@house.gov",
      "gender":"male",
      "mobile":"281-537-7326",
      "cumulativeGPA":66.0,
      "isGraduated":true,
      "friends":[
         {
            "name":"Marwa",
            "email":"mgrewes0@chronoengine.com",
            "gender":"female",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":22,
      "image" : {"name":"ghilk.png", "height": 50, "width":30}
   },
   {
      "id":29,
      "name":"Dev",
      "email":"dsiddons@linkedin.com",
      "gender":"female",
      "mobile":"321-542-4841",
      "cumulativeGPA":63.5,
      "isGraduated":false,
      "friends":[
         {
            "name":"Mohammad",
            "email":"mgrewes0@chronoengine.com",
            "gender":"male",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         }
      ],
      "age":24,
      "image" : {"name":"ghblk.png", "height": 50, "width":30}
   },
   {
      "id":30,
      "name":"Tyson",
      "email":"tkapilofft@sakura.ne.jp",
      "gender":"male",
      "mobile":"881-390-1069",
      "cumulativeGPA":65.6,
      "isGraduated":false,
      "friends":[
         {
            "name":"Alia",
            "email":"mgrewes0@chronoengine.com",
            "gender":"female",
            "mobile":"734-324-1043",
            "cumulativeGPA":92.1
         },
         {
            "name":"Harman",
            "email":"hgaspero2@1688.com",
            "gender":"male",
            "mobile":"158-265-8979",
            "cumulativeGPA":87.9
         },
         {
            "name":"Oliver",
            "email":"ocourtliff4@spotify.com",
            "gender":"female",
            "mobile":"500-958-5193",
            "cumulativeGPA":67.9
         },
         {
            "name":"Rod",
            "email":"romoylanem@omniture.com",
            "gender":"male",
            "mobile":"487-863-3754",
            "cumulativeGPA":83.3
         }
      ],
      "age":24,
      "image" : {"name":"glklk.png", "height": 50, "width":30}
   }
]
   
module.exports =  {users}